# -*- coding: utf-8 -*-
"""analysis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uTJ344vOPOKKgoSQhb8_lsbvV23iFO_R
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("orders.csv")

region_sales = df.groupby("region")["price"].sum()

region_sales.plot(kind="bar")

plt.title("Revenue by Region")
plt.ylabel("Revenue")
plt.xlabel("Region")

plt.show()